FROM python:3.7
RUN pip install tqdm
RUN pip install pandas
RUN pip install numpy
RUN pip install plotly
RUN pip install openpyxl
RUN pip install uvicorn[standard]
RUN pip install fastapi
RUN pip install requests
RUN pip install timeloop
RUN pip install scrapy

